namespace WhiteFilelistManager.PathGenTools.Dirs
{
    internal class ZoneMapping
    {
        public static readonly Dictionary<string, int> XIIIZones = new()
        {
            { "tsiw", 1 },
            { "hgcr", 2 },
            { "hiku", 3 },
            { "vpek", 4 },
            { "btes", 5 },
            { "nati", 6 },
            { "hmob", 7 },
            { "pmpm", 8 },
            { "bodm", 9 },
            { "snls", 10 },
            { "gapr", 15 },
            { "hang", 16 },
            { "hgin", 17 },
            { "fark", 18 },
            { "eden", 19 },
            { "gpst", 20 },
            { "gpcg", 21 },
            { "gpyu", 22 },
            { "gpda", 23 },
            { "gptk", 24 },
            { "grap", 25 },
            { "gptt", 26 },
            { "gpwo", 27 },
            { "high", 28 },
            { "lasd", 29 },
            { "gpoc", 30 },
            { "gpnj", 31 },
            { "gpon", 32 },
            { "gpex", 33 },
            { "ueno", 34 },
            { "hisi", 100 },
            { "fjav", 101 },
            { "ohta", 102 },
            { "matu", 103 },
            { "iioo", 104 },
            { "eark", 105 },
            { "okah", 106 },
            { "miya", 107 },
            { "iwbc", 111 },
            { "hoge", 200 },
            { "tate", 201 },
            { "honm", 203 },
            { "sait", 204 },
            { "isig", 205 },
            { "sndf", 206 },
            { "snde", 207 },
            { "cuts", 208 },
            { "ikik", 209 },
            { "addc", 210 },
            { "test", 255 }
        };


        public static readonly Dictionary<string, int> XIII2Zones = new()
        {
            { "hmaa", 10 },
            { "hmha", 17 },
            { "hmhx", 19 },
            { "bjaa", 20 },
            { "bjba", 21 },
            { "bjda", 23 },
            { "bjea", 24 },
            { "gyaa", 30 },
            { "gyba", 31 },
            { "gyca", 32 },
            { "gyha", 37 },
            { "snda", 43 },
            { "snea", 44 },
            { "sndx", 49 },
            { "gwca", 52 },
            { "gwda", 53 },
            { "gwea", 54 },
            { "gwha", 57 },
            { "gwcx", 59 },
            { "spza", 60 },
            { "spzb", 61 },
            { "spzc", 62 },
            { "spzx", 69 },
            { "clza", 70 },
            { "clzb", 71 },
            { "gdza", 80 },
            { "gdha", 87 },
            { "gdzy", 89 },
            { "gtca", 92 },
            { "gtda", 93 },
            { "gtea", 94 },
            { "gtha", 97 },
            { "gtcx", 99 },
            { "ppea", 104 },
            { "acea", 114 },
            { "acfa", 115 },
            { "acha", 117 },
            { "arba", 121 },
            { "arda", 123 },
            { "area", 124 },
            { "csza", 130 },
            { "cszb", 131 },
            { "ddha", 157 },
            { "vaza", 160 },
            { "vazb", 161 },
            { "hpaa", 170 },
            { "ghaa", 180 },
            { "vpba", 191 },
            { "vpca", 192 },
            { "aaea", 204 },
            { "aaex", 209 },
            { "lsza", 210 },
            { "edxx", 220 },
            { "opxx", 230 },
            { "spxx", 240 },
            { "tbga", 910 },
            { "tbgb", 911 },
            { "tefa", 920 },
            { "test", 930 },
            { "tsda", 940 },
            { "tmoa", 950 },
            { "teva", 960 },
            { "tevb", 961 },
            { "spva", 962 },
            { "tnxa", 971 },
            { "tnxb", 972 },
            { "tnxc", 973 },
            { "tnxd", 974 }
        };


        public static readonly Dictionary<string, int> XIIILRZones = new()
        {
            { "wdaa", 100 },
            { "ptaa", 110 },
            { "lxaa", 120 },
            { "yuaa", 121 },
            { "wlaa", 122 },
            { "ddaa", 123 },
            { "edaa", 124 },
            { "tbga", 910 },
            { "tbgb", 911 },
            { "tbgc", 912 },
            { "tbgd", 913 },
            { "tbge", 914 },
            { "tbgf", 915 },
            { "tbgg", 916 },
            { "tbgh", 917 },
            { "tbgi", 918 },
            { "tpla", 920 },
            { "tplb", 921 },
            { "tplc", 922 },
            { "tpld", 923 },
            { "tbtl", 930 }
        };
    }
}